import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import Stats from '../components/Stats';
import fetchStats from '../utils/fetch-stats';
import { StatsResponse } from '../utils/fetch-stats';

export const getServerSideProps: GetServerSideProps = async () => {
  const stats = await fetchStats();

  return {
    props: {
      stats,
    },
  };
};

const Home: NextPage<{ stats: StatsResponse }> = ({ stats }) => {
  return (
    <div>
      <Head>
        <title>CryptoStats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative w-full min-h-screen flex justify-center p-20">
        <span
          className="bg-opacity-80 bg-center bg-cover absolute inset-0 -z-10"
          style={{
            backgroundImage: 'url(bg.jpg)',
          }}
        ></span>
        <span className="bg-black absolute inset-0 opacity-50 -z-10"></span>
        <div className="container mx-auto bg-white bg-opacity-70 rounded-xl p-20">
          <h1 className="text-xl mb-5">Zarobione pieniążki</h1>
          <Stats stats={stats} />
        </div>
      </div>
    </div>
  );
};

export default Home;
